---
kind: Template
apiVersion: v1
metadata:
  name: redash
labels:
  template: redash-template
parameters:
  - name: POSTGRES_USER
    required: true
    parameterType: string
  - name: POSTGRES_PW
    required: true
    parameterType: string
  - name: POSTGRES_INSTANCE
    required: true
    parameterType: string
  - name: REDASH_COOKIE_SECRET
    required: true
    parameterType: string
objects:
  - kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: redash-init
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: redash-db-init
        spec:
          containers:
            - name: redash-init
              image: redash/redash:latest
              resources:
                requests:
                  memory: 1Gi
              env:
                - name: REDASH_DATABASE_URL
                  value: postgresql://$(POSTGRES_USER):$(POSTGRES_PW)@localhost:5432/redash
                - name: REDASH_REDIS_URL
                  value: "redis://localhost:6379/0"
                - name: PYTHONUNBUFFERED
                  value: "0"
                - name: REDASH_LOG_LEVEL
                  value: "INFO"
              args: ["create_db"]
            - name: redis
              image: redis:3.0-alpine
              ports:
                - name: redis
                  containerPort: 6379
            - name: cloudsql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:1.11
              command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                        "-instances=$(POSTGRES_INSTANCE)=tcp:5432",
                        "-credential_file=/secrets/cloudsql/credentials.json"]
              volumeMounts:
                - name: cloudsql-instance-credentials
                  mountPath: /secrets/cloudsql
                  readOnly: true
                - name: ssl-certs
                  mountPath: /etc/ssl/certs
                - name: cloudsql
                  mountPath: /cloudsql
          volumes:
            - name: cloudsql-instance-credentials
              secret:
                secretName: cloudsql-instance-credentials
            - name: cloudsql
              emptyDir:
            - name: ssl-certs
              hostPath:
                path: /etc/ssl/certs
