---
kind: Template
apiVersion: v1
metadata:
  name: redash-resources-template
parameters:
  - name: POSTGRES_CONN_NAME
    description: "Connection name for CloudSQL instance, e.g. myproject1:us-central1:myinstance1"
    required: true
    parameterType: string
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: redash-resources
    spec:
      type: ClusterIP
      selector:
        app: redash-resources
      ports:
        - name: postgres
          port: 5432
        - name: redis
          port: 6379
  - kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: redash-resources
      labels:
        app: redash-resources
    spec:
      replicas: 1
      template:
        metadata:
          name: redash-resources
          labels:
            app: redash-resources
        spec:
          containers:
            - name: cloudsql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:1.11
              command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                        "-instances=$(POSTGRES_CONN_NAME)=tcp:0.0.0.0:5432",
                        "-credential_file=/secrets/cloudsql/credentials.json"]
              ports:
                - name: postgres
                  containerPort: 5432
              volumeMounts:
                - name: cloudsql-instance-credentials
                  mountPath: /secrets/cloudsql
                  readOnly: true
                - name: ssl-certs
                  mountPath: /etc/ssl/certs
                - name: cloudsql
                  mountPath: /cloudsql
            - name: redis
              image: redis:3.0-alpine
              ports:
                - name: redis
                  containerPort: 6379
              volumeMounts:
                - name: redis-disk
                  mountPath: /data/redis
          volumes:
            - name: cloudsql-instance-credentials
              secret:
                secretName: cloudsql-instance-credentials
            - name: cloudsql
              emptyDir:
            - name: ssl-certs
              hostPath:
                path: /etc/ssl/certs
            - name: redis-disk
              gcePersistentDisk:
                pdName: redash-redis-disk
                fsType: ext4
