---
kind: Template
apiVersion: v1
metadata:
  name: redash-init-template
parameters:
  - name: POSTGRES_USER
    required: true
    parameterType: string
  - name: POSTGRES_PW
    required: true
    parameterType: string
objects:
  - kind: Job
    apiVersion: batch/v1
    metadata:
      name: redash-init
    spec:
      template:
        metadata:
          labels:
            app: redash-init
        spec:
          restartPolicy: Never
          containers:
            - name: redash-init
              image: redash/redash:latest
              resources:
                requests:
                  memory: 1Gi
              env:
                - name: REDASH_DATABASE_URL
                  value: postgresql://$(POSTGRES_USER):$(POSTGRES_PW)@redash-resources:5432/redash
                - name: REDASH_REDIS_URL
                  value: "redis://redash-resources:6379/0"
                - name: PYTHONUNBUFFERED
                  value: "0"
                - name: REDASH_LOG_LEVEL
                  value: "INFO"
              args: ["create_db"]
